name: Deploy ADF to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'adf_publish/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy ADF ARM Template
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        resourceGroupName: ${{ secrets.RESOURCE_GROUP_NAME }}
        template: ./adf_publish/ARMTemplateForFactory.json
        parameters: ./adf_publish/ARMTemplateParametersForFactory.json
        deploymentName: ADFDeploy-${{ github.run_number }}
        region: ${{ secrets.LOCATION }}
